fix: remove appium test android

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -33,27 +33,27 @@ jobs:
       - run:
           name: Build APK
           command: cd android && ./gradlew assembleDebug
-      - run:
-          name: App upload and Set app id in environment variable.
-          command: |
-            cd android
-            APP_UPLOAD_RESPONSE=$(curl -u "$BROWSERSTACK_USER:$BROWSERSTACK_ACCESS_KEY" -X POST https://api-cloud.browserstack.com/app-automate/upload -F "file=@app/build/outputs/apk/debug/app-debug.apk")
-            APP_ID=$(echo $APP_UPLOAD_RESPONSE | jq -r ".app_url")
-            if [ $APP_ID != null ]; then
-              echo "Apk uploaded to BrowserStack with app id : ",$APP_ID;
-              echo "export BROWSERSTACK_APP_ID=$APP_ID" >> $BASH_ENV;
-              source $BASH_ENV;
-              echo "Setting value of BROWSERSTACK_APP_ID in environment variables to  ",$APP_ID;
-            else
-              UPLOAD_ERROR_MESSAGE=$(echo $APP_UPLOAD_RESPONSE | jq -r ".error")
-              echo "App upload failed, reason : ",$UPLOAD_ERROR_MESSAGE
-              exit 1;
-            fi
-      - run:
-          name: Run Test on Android
-          command: |
-            yarn start &
-            ./node_modules/.bin/wdio android/browserstack.js
+      # - run:
+      #     name: App upload and Set app id in environment variable.
+      #     command: |
+      #       cd android
+      #       APP_UPLOAD_RESPONSE=$(curl -u "$BROWSERSTACK_USER:$BROWSERSTACK_ACCESS_KEY" -X POST https://api-cloud.browserstack.com/app-automate/upload -F "file=@app/build/outputs/apk/debug/app-debug.apk")
+      #       APP_ID=$(echo $APP_UPLOAD_RESPONSE | jq -r ".app_url")
+      #       if [ $APP_ID != null ]; then
+      #         echo "Apk uploaded to BrowserStack with app id : ",$APP_ID;
+      #         echo "export BROWSERSTACK_APP_ID=$APP_ID" >> $BASH_ENV;
+      #         source $BASH_ENV;
+      #         echo "Setting value of BROWSERSTACK_APP_ID in environment variables to  ",$APP_ID;
+      #       else
+      #         UPLOAD_ERROR_MESSAGE=$(echo $APP_UPLOAD_RESPONSE | jq -r ".error")
+      #         echo "App upload failed, reason : ",$UPLOAD_ERROR_MESSAGE
+      #         exit 1;
+      #       fi
+      # - run:
+      #     name: Run Test on Android
+      #     command: |
+      #       yarn start &
+      #       ./node_modules/.bin/wdio android/browserstack.js
 
   ios_test:
     macos:
